env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
globals:
  expect: true
  should: true
  it: true
extends: airbnb-base
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: ["error", { allow: ["warn", "error", "info", "log"] }]
